name: Query CT OBS Systems
on: push
jobs:
  render:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
      - name: Set up pandoc
        uses: r-lib/actions/setup-pandoc@v2-branch
      - name: Install dependencies
        run: |
          install.packages("renv", type = "win.binary")
          renv::restore(prompt = F)
        shell: Rscript {0}
      - name: Script
        run: Rscript dev_pb_query_process.R
      - name: Commit files
        run: |
          git add .
          git commit -m "data query commit on $(date)" || echo "No changes to commit"
          git push origin || echo "No changes to commit"
